version: '3.8'

services:
  frontend-dev:
    container_name: mini-notion-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
    stdin_open: true
    tty: true
    networks:
      - mini-notion-network

networks:
  mini-notion-network:
    driver: bridge
